name: Basic Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Basic Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        python -c "import app; print('✅ App imports successfully')"
        python -c "from app import create_app; app = create_app(); print('✅ App creates successfully')"
    
    - name: Test API health check
      run: |
        python -c "
        from app import create_app
        app = create_app()
        with app.test_client() as client:
            response = client.get('/api/health')
            print('✅ Health check:', response.status_code)
        "